version: "3"

services:
  rabbit:
    container_name: crawler-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped

  nginx:
    container_name: crawler-nginx
    build: ./nginx
    links:
      - app:app
    ports:
      - 7777:7777
    depends_on:
      - app
    restart: unless-stopped

  app:
    container_name: crawler-app
    build: .
    depends_on:
      - rabbit
    links:
      - rabbit:rabbit
    ports:
      - 8080:8080
    restart: unless-stopped

  consumer:
    container_name: crawler-worker
    build:
      context: .
      dockerfile: Workerdocker
    depends_on:
      - rabbit
    links:
      - rabbit:rabbit
    restart: unless-stopped
